[workspace]
resolver = "2"
members = [
    "crates/rqbit",
    "crates/librqbit",
    "crates/buffers",
    "crates/clone_to_owned",
    "crates/bencode",
    "crates/sha1w",
    "crates/librqbit_core",
    "crates/librqbit_lsd",
    "crates/peer_binary_protocol",
    "crates/dht",
    "crates/upnp",
    "crates/tracker_comms",
    "crates/upnp-serve",
    "desktop/src-tauri",
]

# Everything except desktop
default-members = [
    "crates/rqbit",
    "crates/librqbit",
    "crates/buffers",
    "crates/clone_to_owned",
    "crates/bencode",
    "crates/sha1w",
    "crates/librqbit_core",
    "crates/peer_binary_protocol",
    "crates/dht",
    "crates/upnp",
    "crates/tracker_comms",
    "crates/upnp-serve",
]

[profile.dev]
panic = "abort"
incremental = true # Compile your binary in smaller steps.

[profile.release]
panic = "abort"
debug = false
lto = "thin"
# See https://tauri.app/concept/size/#cargo-configuration
strip = true # Ensures debug symbols are removed.
opt-level = "s" # Prioritizes small binary size. Use `3` if you prefer speed.
codegen-units = 1 # Allows LLVM to perform better optimization.

[profile.release-github]
inherits = "release"
lto = false

[profile.release-debug]
inherits = "release"
debug = true
